### PR TITLE
Fix XSM policy to allow PCI passthrough to stubdoms with flask enforcing

### PR DESCRIPTION
**Pull request by brendank310**
Adds policy to allow stubdom the ability to add,remove, and bind irq's for 'device_t' resources.

### CODE REVIEW

**Comment by brendank310** [comment]
@flihp can you give this a look over to see that I'm not giving the stubdom more privilege than is necessary for passthrough to function.

**Comment by flihp** [comment]
What's the use-case for this? Is there a JIRA ticket where I can read up on this? The policy looks clean but some context would be helpful.

**Comment by brendank310** [comment]
Sorry no JIRA ticket. Eric had done work on fixing PCI passthrough within the stubdom within QEmu 1.4, and these denials were preventing that from functioning while flask was set to enforcing:

(XEN) avc:  denied  { add_irq } for domid=4 device=0x100 scontext=system_u:system_r:stubdom_t tcontext=system_u:object_r:device_t tclass=resource
(XEN) avc:  denied  { bind_irq } for domid=4 device=0x100 scontext=system_u:system_r:stubdom_t tcontext=system_u:object_r:device_t tclass=hvm

Additionally if a domain dies that has it's device model in a stubdomain a similar denial for remove_irq is logged.

There may be a more concise way to go about this, perhaps just piggybacking on the existing pirq interfaces, and adding device_t to it also, but that's a little beyond my SELinux/XSM knowledge.

**Comment by brendank310** [comment]
@flihp I've merged this into the layer for now, can you give it another look over when a the pull request against xsm-policy.git is generated for flattening the layer into the main build?

**Comment by flihp** [comment]
Sounds good @brendank310. A few quick thoughts:

1) Patch looks clean.
2) If all access are related I think it would be reasonable to combine all of the 'allow' rules into one interface. Something like "passthrough_device' or whatever.
3) Do we know why this new version of QEMU requires these accesses where the old version didn't? We're not adding some new features that would require these new accesses, just the same functionality as before but with a new version of qemu?

There's a lot about the XSM policy (and the Xen object model) that I don't understand so some of this may just be my ignorance showing. Let me know what you think.

**Comment by brendank310** [comment]
I think this patch will probably get rolled back. There is an existing interface, 'dom0_pt_guest' that both the ndvm and hvm guest types are labelled as, which should probably be used by the stubdom instead. As far as the object label, in upstream Xen's reference policy it says device_t is 'unlabeled'. I'll look at that today, and see if perhaps the label is just not getting applied.

**Pull request merged**
